/** @format */

import { Html, Head, Main, NextScript } from "next/document";
import Script from 'next/script';



export default function Document() {
  return (
    <Html lang='en'>
      <Head>
        <title>Filscan--Filecoin区块链浏览器</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /> 
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0, minimum-scale=1,user-scalable=no'
        />
        <meta
          name='keywords'
          content='Filecoin官方区块浏览器,Filecoin官方浏览器, Filscan,Filecoin,最新区块,Filecoin Explorer,FIL,IPFS，FIL,Filecoin区块链查询浏览器,FIL浏览器,Filecoin浏览器,Filecoin区块查询,区块链搜索引擎,区块高度,区块链交易'
        />
          <meta
          name='keywords'
          content='Filecoin,fvm, explorer, ether, search, blockchain, crypto, currency'
        />
        <meta
          name='description'
          content='Filscan区块浏览器是Filecoin生态基础工具，提供实时链上相关数据。集查询Filecoin区块、交易、FIL代币、钱包等信息的网站，实时同步更新Filecoin所有节点信息。'
        />
        
        <link rel='icon' href='/favicon.ico' />
        {/* <link rel='icon' href='/logo.svg' /> */}
        <script type="text/javascript" id='umeng' src="https://s9.cnzz.com/z_stat.php?id=1281274057&web_id=1281274057"></script>
      </Head>
      <body>
        <NextScript />
      </body>
    </Html>
  );
}
